imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false
# Doctrine MongoDB
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb.server%"
            options: {}
    default_database: "test_nasa"
    document_managers:
        default:
            auto_mapping: true
