neo_test:
    resource: "@NeoTestBundle/Controller/"
    type:     annotation
    prefix:   /

nasa:
    resource: "@NasaBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
